### ISSUE TITLE
changing the PdPatch and rebuilding has no effect

### ISSUE THREAD

**Issue by umlaeute** [charlesneimog/pd4web#10]
after changing the `Patches/index.pd`, some special steps need to be taken in order for the patch to actually show up in the webpage.

as per https://github.com/pure-data/pure-data/issues/2258#issuecomment-2052498934, these steps should be something like:

```sh
emcmake cmake . -B build
emmake make -C build -j 8
```

however, it seems that this is not enough (as in: reloading the page and restarting the patch  will still use the *old* patch)

afaict, i also need to change "something" in the source-code and re-compile (since i was working on Pd itself, something like `build/libpd/pure-data/src/x_time.c` would do the trick).

as assume this is because `webpatch/pd4web.js` (which i guess contains both the patch and the Pd wasm code) is only rebuilt if the .c sources change, but not if only the .pd file changes.

**Comment by charlesneimog** [comment]
```
emcmake cmake . -B build
emmake make -C build -j 8
```

Should be enough now!
