### ISSUE TITLE
[else/allpass.rev~] errors

### ISSUE THREAD

**Issue by luismrguimaraes** [charlesneimog/pd4web#21]
Hi, my patch compiles successfully, but I get these error messages and am unable to hear the reverb I have in my patch. The issue is with the [else/plate.rev~] object, and the first error is from the `[else/compress~]` object.

<img width="491" alt="image" src="https://github.com/user-attachments/assets/0c72bc9d-aa7f-46b1-900b-4ad292841972">

**Comment by charlesneimog** [comment]
I think it was fixed, let me know

**Comment by luismrguimaraes** [comment]
`[else/plate.rev~]` still gives me the same error. I'm trying this patch:
```pd
#N canvas 324 361 899 487 12;
#N canvas 520 509 838 404 plateVerb 0;
#X obj 71 15 inlet~;
#X obj 111 194 outlet~;
#X obj 152 11 inlet;
#X obj 125 112 else/plate.rev~;
#X obj 200 195 outlet~;
#X obj 203 13 loadbang;
#X msg 230 46 damp 0.25;
#X msg 128 51 wet \$1;
#X msg 250 72 size 0.01;
#X connect 0 0 3 0;
#X connect 2 0 7 0;
#X connect 3 0 1 0;
#X connect 3 1 4 0;
#X connect 5 0 6 0;
#X connect 6 0 3 0;
#X connect 7 0 3 0;
#X connect 8 0 3 0;
#X restore 306 21 pd plateVerb;
```

**Comment by luismrguimaraes** [comment]
The `[else/compress~]` inside the subpatch also gives the same error as before.

**Comment by luismrguimaraes** [comment]
[else/comb.rev~] (inside a subpatch) is also throwing errors in the browser :'(

**Comment by luismrguimaraes** [comment]
I'm constantly finding objects that give errors. Is it okay if I create a discussion for objects that don't work?

**Comment by charlesneimog** [comment]
Of course! 

I found the problem, but it requires rewriting how pd4web finds the externals of the patch, so it will take some days...

But knowing the objects that don't work would be great. Also, if you have some examples with patches it will help me a little more...

Thank you for all the feedback!
