### ISSUE TITLE
question about p5js support 

### ISSUE THREAD

**Issue by jyg** [charlesneimog/pd4web#6]
Hi,
I was just trying  to use pd4web with p5js since 2 weeks with some results  (https://jyg.github.io/carto_p5/webpatch/index.html, source code here https://github.com/jyg/carto_p5) and I just saw that you put an example in your readme file ("interaction with p5js").
Did you put any code somewhere related to this ?
I would be **very** interested !
Thanks and congrats for your work. It's a game changer for pd web-integration !

**Comment by charlesneimog** [comment]
Hi @jyg, thanks for using `pd4web`, if you find a bug, please report it... 

Yes, there is an example, but I believe it is a different use, I was using it just to show a poem while people improvised. There are some hidden commands (like `a`, `b`, and `c`) to trigger the processes.

If you see the improvisation guide you will understand! https://charlesneimog.github.io/Projeto/.

* Here I define the Sketch div and load the puredata = https://github.com/charlesneimog/Projeto/blob/main/poemas/index.html#L25;

* Here is the sketch
https://github.com/charlesneimog/Projeto/blob/main/poemas/mySketch.js#L1092
